name: notebooks_in_vscode_and_pycharm_jan_2020
channels:
  - default
  - conda-forge
dependencies:
  - python==3.7
  - jupyterlab
  - jupytext
  - autopep8
  - pylint
  - flake8
  - pandas
  - numpy
  - matplotlib
  - ipywidgets
  - plotly
  - pytest
  - pytest-xdist
  - pip
  - setuptools
  - pip:
    - world_bank_data
    - easyplotly
